// Code generated by hack/gen_config_version_metadata.py. DO NOT EDIT.
//
// Regenerate with:
//   hack/gen_config_version_metadata.py --valkey-repo <path> --baseline 8.1.0 --out <this file>
//
// Lists directives introduced after 8.1.0, up to 9.1.0.

package valkey

import semver "github.com/Masterminds/semver/v3"

// ConfigIntroducedIn maps user-facing config directives to the minimum
// Valkey version that understands them. Only directives introduced after
// the 8.1.0 baseline are listed; anything not present is assumed
// supported by every Valkey version the operator supports.
var ConfigIntroducedIn = map[string]*semver.Version{
	"cluster-announce-client-port":           semver.MustParse("9.0.0"),
	"cluster-announce-client-tls-port":       semver.MustParse("9.0.0"),
	"cluster-config-save-behavior":           semver.MustParse("9.1.0"),
	"cluster-databases":                      semver.MustParse("9.0.0"),
	"cluster-slot-migration-log-max-len":     semver.MustParse("9.0.0"),
	"hash-seed":                              semver.MustParse("9.1.0"),
	"mptcp":                                  semver.MustParse("9.0.0"),
	"repl-mptcp":                             semver.MustParse("9.0.0"),
	"slot-migration-max-failover-repl-bytes": semver.MustParse("9.0.0"),
	"tls-auth-clients-user":                  semver.MustParse("9.0.0"),
	"tls-auto-reload-interval":               semver.MustParse("9.1.0"),
}
