immutable_configs:
  - rdbchecksum
  - daemonize
  - always-show-logo
  - set-proc-title
  - repl-mptcp
  - syslog-enabled
  - cluster-enabled
  - disable-thp
  - enable-debug-assert
  - aclfile
  - unixsocket
  - unixsocketgroup
  - pidfile
  - cluster-config-file
  - syslog-ident
  - appendfilename
  - appenddirname
  - server-cpulist
  - bio-cpulist
  - aof-rewrite-cpulist
  - bgsave-cpulist
  - logfile
  - req-res-logfile
  - hash-seed
  - supervised
  - syslog-facility
  - enable-protected-configs
  - enable-debug-command
  - enable-module-command
  - databases
  - cluster-databases
  - tcp-backlog
  - mptcp
  - cluster-port
  - rdma-rx-size
  - rdma-completion-vector
  - unixsocketperm
  - socket-mark-id
  - client-default-resp
  - replicaof
modifiable_configs:
  - protected-mode
  - rdbcompression
  - rdb-del-sync-files
  - activerehashing
  - stop-writes-on-bgsave-error
  - lazyfree-lazy-eviction
  - lazyfree-lazy-expire
  - lazyfree-lazy-server-del
  - lazyfree-lazy-user-del
  - lazyfree-lazy-user-flush
  - repl-disable-tcp-nodelay
  - repl-diskless-sync
  - dual-channel-replication-enabled
  - aof-rewrite-incremental-fsync
  - no-appendfsync-on-rewrite
  - cluster-require-full-coverage
  - rdb-save-incremental-fsync
  - aof-load-truncated
  - aof-use-rdb-preamble
  - aof-timestamp-enabled
  - cluster-replica-no-failover
  - replica-lazy-flush
  - replica-serve-stale-data
  - replica-read-only
  - replica-ignore-maxmemory
  - jemalloc-bg-thread
  - activedefrag
  - appendonly
  - cluster-allow-reads-when-down
  - cluster-allow-pubsubshard-when-down
  - crash-log-enabled
  - crash-memcheck-enabled
  - use-exit-on-panic
  - cluster-allow-replica-migration
  - replica-announced
  - latency-tracking
  - aof-disable-auto-gc
  - replica-ignore-disk-write-errors
  - extended-redis-compatibility
  - cluster-slot-stats-enabled
  - hide-user-data-from-log
  - lua-enable-insecure-api
  - import-mode
  - io-threads-always-active
  - replica-announce-ip
  - primaryuser
  - cluster-announce-ip
  - cluster-announce-client-ipv4
  - cluster-announce-client-ipv6
  - cluster-announce-hostname
  - cluster-announce-human-nodename
  - dbfilename
  - ignore-warnings
  - proc-title-template
  - bind-source-addr
  - locale-collate
  - debug-context
  - primaryauth
  - requirepass
  - availability-zone
  - repl-diskless-load
  - loglevel
  - maxmemory-policy
  - appendfsync
  - oom-score-adj
  - acl-pubsub-default
  - sanitize-dump-payload
  - cluster-preferred-endpoint-type
  - cluster-config-save-behavior
  - propagation-error-behavior
  - shutdown-on-sigint
  - shutdown-on-sigterm
  - log-format
  - log-timestamp-format
  - rdb-version-check
  - port
  - io-threads
  - min-io-threads-avoid-copy-reply
  - min-string-size-avoid-copy-reply
  - min-string-size-avoid-copy-reply-threaded
  - prefetch-batch-max-size
  - auto-aof-rewrite-percentage
  - cluster-replica-validity-factor
  - list-max-listpack-size
  - tcp-keepalive
  - cluster-migration-barrier
  - active-defrag-cycle-min
  - active-defrag-cycle-max
  - active-defrag-threshold-lower
  - active-defrag-threshold-upper
  - active-defrag-cycle-us
  - lfu-log-factor
  - lfu-decay-time
  - replica-priority
  - repl-diskless-sync-delay
  - maxmemory-samples
  - maxmemory-eviction-tenacity
  - timeout
  - replica-announce-port
  - cluster-announce-bus-port
  - cluster-announce-port
  - cluster-announce-tls-port
  - cluster-announce-client-port
  - cluster-announce-client-tls-port
  - repl-timeout
  - repl-ping-replica-period
  - list-compress-depth
  - rdb-key-save-delay
  - key-load-delay
  - active-expire-effort
  - hz
  - min-replicas-to-write
  - min-replicas-max-lag
  - watchdog-period
  - shutdown-timeout
  - repl-diskless-sync-max-replicas
  - rdma-port
  - cluster-message-gossip-perc
  - maxclients
  - max-new-connections-per-cycle
  - max-new-tls-connections-per-cycle
  - active-defrag-max-scan-fields
  - commandlog-slow-execution-max-len
  - commandlog-large-request-max-len
  - commandlog-large-reply-max-len
  - acllog-max-len
  - cluster-blacklist-ttl
  - cluster-slot-migration-log-max-len
  - busy-reply-threshold
  - cluster-node-timeout
  - cluster-ping-interval
  - commandlog-execution-slower-than
  - commandlog-request-larger-than
  - commandlog-reply-larger-than
  - latency-monitor-threshold
  - proto-max-bulk-len
  - stream-node-max-entries
  - repl-backlog-size
  - cluster-manual-failover-timeout
  - maxmemory
  - cluster-link-sendbuf-limit
  - hash-max-listpack-entries
  - set-max-intset-entries
  - set-max-listpack-entries
  - set-max-listpack-value
  - zset-max-listpack-entries
  - active-defrag-ignore-bytes
  - hash-max-listpack-value
  - stream-node-max-bytes
  - zset-max-listpack-value
  - hll-sparse-max-bytes
  - tracking-table-max-keys
  - client-query-buffer-limit
  - maxmemory-clients
  - slot-migration-max-failover-repl-bytes
  - repl-backlog-ttl
  - auto-aof-rewrite-min-size
  - loading-process-events-interval-bytes
  - tls-port
  - tls-session-cache-size
  - tls-session-cache-timeout
  - tls-auto-reload-interval
  - tls-cluster
  - tls-replication
  - tls-auth-clients
  - tls-auth-clients-user
  - tls-prefer-server-ciphers
  - tls-session-caching
  - tls-cert-file
  - tls-key-file
  - tls-key-file-pass
  - tls-client-cert-file
  - tls-client-key-file
  - tls-client-key-file-pass
  - tls-dh-params-file
  - tls-ca-cert-file
  - tls-ca-cert-dir
  - tls-protocols
  - tls-ciphers
  - tls-ciphersuites
  - dir
  - save
  - client-output-buffer-limit
  - oom-score-adj-values
  - notify-keyspace-events
  - bind
  - rdma-bind
  - latency-tracking-info-percentiles