## Append samples of your project ##
resources:
- v1alpha1_valkeycluster.yaml
- v1alpha1_valkeycluster-persistent.yaml
- v1alpha1_valkeycluster-external-access.yaml
- v1alpha1_valkeycluster-gateway.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
