name: Lint

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: go.mod

      - name: Check linter configuration
        run: make lint-config

      - name: Run linter
        run: make lint

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: go.mod
      - name: Check using gofmt
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Go code is not formatted with gofmt:"
            gofmt -s -d .
            exit 1
          fi

  mod-tidy:
    name: Check go.mod
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: go.mod
      - name: Check using go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  generated:
    name: Verify generated code
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: go.mod
      - name: Check that generated code is committed
        run: |
          make manifests
          make generate
          git diff --exit-code
